### ISSUE TITLE
Register circuit fails when injecting input a second time

### ISSUE THREAD

**Issue by ttoktassynov** [node-red-quantum/node-red-contrib-quantum#126]
### Bug Description
When injecting input to the register only circuit a second time in a row, after first successful input, we receive following error of Quantum Register:
```
(node:87745) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:87745) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:87745) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'push' of undefined
    at ClassicalRegisterNode._inputCallback (/Users/ttoktassynov/projects/nodejs_projects/node-red-contrib-quantum/nodes/quantum/classical-register/classical-register.js:45:19)
    at /Users/ttoktassynov/projects/nodejs_projects/node-red-contrib-quantum/node_modules/@node-red/runtime/lib/nodes/Node.js:203:26
    at Object.trigger (/Users/ttoktassynov/projects/nodejs_projects/node-red-contrib-quantum/node_modules/@node-red/runtime/lib/hooks.js:113:9)
    at ClassicalRegisterNode.Node._emitInput (/Users/ttoktassynov/projects/nodejs_projects/node-red-contrib-quantum/node_modules/@node-red/runtime/lib/nodes/Node.js:195:11)
    at ClassicalRegisterNode.Node.emit (/Users/ttoktassynov/projects/nodejs_projects/node-red-contrib-quantum/node_modules/@node-red/runtime/lib/nodes/Node.js:179:25)
    at ClassicalRegisterNode.Node.receive (/Users/ttoktassynov/projects/nodejs_projects/node-red-contrib-quantum/node_modules/@node-red/runtime/lib/nodes/Node.js:476:10)
    at Immediate.<anonymous> (/Users/ttoktassynov/projects/nodejs_projects/node-red-contrib-quantum/node_modules/@node-red/runtime/lib/flows/Flow.js:679:52)
    at processImmediate (internal/timers.js:461:21)
(node:87745) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

```

Most likely it has to do with state management functionanility.

### Steps to Reproduce Bug

Draw this circuit:
![Screen Shot 2021-09-07 at 21 50 14](https://user-images.githubusercontent.com/25239936/132409119-bafaab1c-b613-4965-9ed3-77d4aa4a4590.png)

or simply import this [json](https://pastebin.com/aSzHf9YE)

### Additional Information

Log file can be found [here](https://pastebin.com/r5keA8Ye).

### System Information

* **Node.js Version**: v12.22.1

* **Operating System**:Darwin tma.local 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64

**Comment by louislefevre** [comment]
Seems to be caused by the `registerArr` variable in `quantum-register.js`. On first execution, its initial value is `[]`. On second execution, its initial value is `undefined`.

Also, it's worth noting that this behaviour happens in the same loop:
- First execution is successful.
- Second execution fails.
- Third execution is successful.
- Fourth execution fails.

**Comment by louislefevre** [comment]
Okay so I think I figured out the cause. This is the flow of execution:
- `quantum-circuit` node is loaded, initialising `registers` to an empty array in the global state.
- The flow is run for the first time, and at some point `state.del('registers')` is executed, setting `registers` to `undefined`. The flow still finishes executing successfully.
- The flow is run for the second time, BUT because `quantum-circuit` has not been re-loaded (therefore initialising `registers` to an empty array again), `registers` is still left as `undefined` from the previous run.
- Due to `registers` being undefined, an error occurs in Node-RED. Node-RED will automatically restart everything when this happens, which in turn causes `quantum-circuit` nodes to be re-loaded, thereby initialising `registers` to an empty array again. So the reason every other execution works is because Node-RED is automatically restarting everything behind the scenes.

A fix I've just quickly tested that seems to work is to replace all instances of `state.del('registers')` with `state.setPersistent('registers', [])`. However, I'm not sure if this will have any unforeseen consequences, since `registers` is no longer removed completely like it was before.

**Comment by ttoktassynov** [comment]
Maybe try to implement in different branch and see if tests pass?

**Comment by louislefevre** [comment]
> Maybe try to implement in different branch and see if tests pass?

The tests still pass locally, but since we don't have tests for all scenarios I'm still unsure as I don't know the reason for deleting 'registers' from the state in the first place.
